spring.config.import=optional:file:./.env[.properties]

server.port=8080
server.servlet.context-path=/api/v1
spring.application.name=backend

spring.mvc.problem-details.enabled=true
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.default-property-inclusion=non_null
spring.jackson.datatype.datetime.write-dates-as-timestamps=false

jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:3000000}
jwt.secret=${JWT_SECRET:my_super_secret_key_for_formula1_app_which_is_long_enough_2026}
jwt.issuer=${JWT_ISSUER:formula1}
jwt.audience=${JWT_AUDIENCE:formula1}

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.cache.type=simple

spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.jdbc.schema-initialization.enabled=true

formula1.notification.email.host=smtp.gmail.com
formula1.notification.email.port=587
formula1.notification.email.username=${MAIL_USERNAME}
formula1.notification.email.password=${MAIL_PASSWORD}
formula1.notification.email.auth=true
formula1.notification.email.starttls-enable=true
formula1.notification.email-token-expiry-hours=${EMAIL_TOKEN_EXPIRY_DATE:24}
formula1.notification.phone-token-expiry-hours=${PHONE_TOKEN_EXPIRY_DATE:24}
formula1.notification.whatsapp.token=${META_ACCESS_TOKEN:dev-token}
formula1.notification.whatsapp.phone-number-id=${PHONE_NUMBER_ID:0}
formula1.notification.whatsapp.api-url=https://graph.facebook.com/v25.0
formula1.notification.enabled=true

spring.profiles.active=dev