spring.config.import=optional:file:./.env[.properties]

server.port=8080
server.servlet.context-path=/api/v1
spring.application.name=identity
spring.mvc.problem-details.enabled=true
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.default-property-inclusion=non_null
spring.jackson.datatype.datetime.write-dates-as-timestamps=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8

jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:3000000}
jwt.secret=${JWT_SECRET:my_super_secret_key_for_formula1_app_which_is_long_enough_2026}
jwt.issuer=${JWT_ISSUER:formula1}
jwt.audience=${JWT_AUDIENCE:formula1}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.token.expiry.date=${EMAIL_TOKEN_EXPIRY_DATE:24}
phone.token.expiry.date=${PHONE_TOKEN_EXPIRY_DATE:24}
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

whatsapp.api.token=${META_ACCESS_TOKEN}
whatsapp.api.phone-number-id=${PHONE_NUMBER_ID}
whatsapp.api.url=https://graph.facebook.com/v25.0
