server.servlet.context-path=/api/v1
spring.application.name=core
spring.mvc.problem-details.enabled=true
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.default-property-inclusion=non_null
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
spring.messages.basename=messages
spring.messages.encoding=UTF-8
